chore(dockerfile): Devonctianer linting

diff --git a/compose/local/django/Dockerfile b/compose/local/django/Dockerfile
--- a/compose/local/django/Dockerfile
+++ b/compose/local/django/Dockerfile
@@ -13,11 +13,13 @@ RUN apt-get update && apt-get install --no-install-recommends -y \
   # psycopg2 dependencies
   libpq-dev
 
+WORKDIR /tmp
+
 # Requirements are installed here to ensure they will be cached.
 COPY ./requirements .
 
 # Create Python Dependency and Sub-Dependency Wheels.
-RUN --mount=type=cache,target=~/.cache \
+RUN --mount=type=cache,target=/home/root/.cache/pip \
   pip wheel --wheel-dir /usr/src/app/wheels  \
   -r ${BUILD_ENVIRONMENT}.txt
 
@@ -31,20 +33,17 @@ ENV PYTHONUNBUFFERED 1
 ENV PYTHONDONTWRITEBYTECODE 1
 ENV BUILD_ENV ${BUILD_ENVIRONMENT}
 
-
-# devcontainer dependencies and utils
-RUN apt-get update && apt-get install --no-install-recommends -y \
-  sudo git bash-completion nano ssh
-
-# Create devcontainer user and add it to sudoers
-RUN groupadd --gid 1000 dev-user \
-  && useradd --uid 1000 --gid dev-user --shell /bin/bash --create-home dev-user \
-  && echo dev-user ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/dev-user \
-  && chmod 0440 /etc/sudoers.d/dev-user
+# Allow piped commands to fail at any step and run, log command
+SHELL ["/bin/bash", "-ceux", "-o", "pipefail"]
 
 
 # Install required system dependencies
 RUN apt-get update && apt-get install --no-install-recommends -y \
+  sudo \
+  git \
+  bash-completion \
+  nano \
+  ssh \
   # Commits signing dependencies
   gnupg2 \
   # Heroku CLI dependencies
@@ -60,12 +59,15 @@ RUN apt-get update && apt-get install --no-install-recommends -y \
 # Install Heroku CLI
 RUN curl https://cli-assets.heroku.com/install.sh | sh
 
-# Bash theme
-RUN sudo -u dev-user bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
-
 # All absolute dir copies ignore workdir instruction. All relative dir copies are wrt to the workdir instruction
 # copy python dependency wheels from python-build-stage
 COPY --from=python-build-stage /usr/src/app/wheels  /wheels/
+
+# Create devcontainer user and add it to sudoers
+RUN groupadd --gid 1000 dev-user \
+  && useradd --uid 1000 --gid dev-user --shell /bin/bash --create-home dev-user \
+  && echo dev-user ALL=\(root\) NOPASSWD:ALL > /etc/sudoers.d/dev-user \
+  && chmod 0440 /etc/sudoers.d/dev-user
 
 # use wheels to install python dependencies
 RUN pip install --no-cache-dir --no-index --find-links=/wheels/ /wheels/* \
@@ -73,23 +75,26 @@ RUN pip install --no-cache-dir --no-index --find-links=/wheels/ /wheels/* \
 
 USER dev-user
 
+# Bash theme
+RUN bash -c "$(curl -fsSL https://raw.githubusercontent.com/ohmybash/oh-my-bash/master/tools/install.sh)"
+
 WORKDIR ${APP_HOME}
 
 COPY .pre-commit-config.yaml .
 RUN git init .
-RUN --mount=type=cache,target=~/.cache,uid=1000 \
-  pre-commit install --install-hooks
-RUN mv .git/hooks $HOME
+RUN --mount=type=cache,target=/home/dev-user/.cache/pre-commit,uid=1000 \
+  pre-commit install --install-hooks \
+  && mv ".git/hooks" "/home/dev-user"
 
 USER root
 
 COPY ./compose/production/django/entrypoint /entrypoint
-RUN sed -i 's/\r$//g' /entrypoint
-RUN chmod +x /entrypoint
+RUN sed -i 's/\r$//g' /entrypoint \
+  && chmod +x /entrypoint
 
 COPY ./compose/local/django/start /start
-RUN sed -i 's/\r$//g' /start
-RUN chmod +x /start
+RUN sed -i 's/\r$//g' /start \
+  && chmod +x /start
 
 USER dev-user
 
